<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TransformOnBuild>true</TransformOnBuild>
    <TransformOutOfDateOnly>false</TransformOutOfDateOnly>
  </PropertyGroup>

  <ItemGroup>
    
    <None Include="BuildTime.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>BuildTime.txt</LastGenOutput>
    </None>
    
    <None Include="LICENSE.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>LICENSE.txt</LastGenOutput>
    </None>

    <None Include="Readme.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>Readme.md</LastGenOutput>
    </None>
    
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

  <Target Name="PreBuild" BeforeTargets="PreBuildEvent" Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <Message Importance="High" Text="Обновление BuildTime.txt перед сборкой PasswordGenerator..." />
    <Exec Command="&quot;$(DevEnvDir)TextTransformCore.exe&quot; &quot;$(ProjectDir)BuildTime.tt&quot; -out &quot;$(SolutionDir)BuildTime.txt&quot;" />
    <Message Importance="High" Text="Обновление LICENSE.txt перед сборкой PasswordGenerator..." />
    <Exec Command="&quot;$(DevEnvDir)TextTransformCore.exe&quot; &quot;$(ProjectDir)LICENSE.tt&quot; -out &quot;$(SolutionDir)LICENSE.txt&quot;" />
    <Message Importance="High" Text="Обновление README.md перед сборкой PasswordGenerator..." />
    <Exec Command="&quot;$(DevEnvDir)TextTransformCore.exe&quot; &quot;$(ProjectDir)Readme.tt&quot; -out &quot;$(SolutionDir)Readme.md&quot;" />
  </Target>


</Project>