<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TransformOnBuild>true</TransformOnBuild>
    <TransformOutOfDateOnly>false</TransformOutOfDateOnly>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="..\BuildTime.txt">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>BuildTime.tt</DependentUpon>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="..\LICENSE.txt">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>LICENSE.tt</DependentUpon>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>   
    <None Include="..\BuildTime.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>BuildTime.txt</LastGenOutput>
    </None>
    
    <None Include="..\LICENSE.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>LICENSE.txt</LastGenOutput>
    </None>

    <None Include="..\LICENSE.txt">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>LICENSE.tt</DependentUpon>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    
    <None Include="..\Readme.md">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Readme.tt</DependentUpon>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\Readme.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>Readme.md</LastGenOutput>
    </None>
  </ItemGroup>


  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

</Project>
