<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AutoGenerateBindingRedirects>True</AutoGenerateBindingRedirects>
    <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
    <EnableNETAnalyzers>True</EnableNETAnalyzers>
    <AnalysisLevel>preview-recommended</AnalysisLevel>
    <OverwriteReadOnlyOutputFiles>true</OverwriteReadOnlyOutputFiles>
    <TransformOutOfDateOnly>false</TransformOutOfDateOnly>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <IsPublishable>False</IsPublishable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <IsPublishable>True</IsPublishable>
  </PropertyGroup>

  <PropertyGroup>
    <Year>$([System.DateTime]::UtcNow.Year.ToString())</Year>
  </PropertyGroup>

  <PropertyGroup>
    <Authors>Kozupitsa DmA</Authors>
    <AssemblyName>DimSaratov.PasswordGenerator</AssemblyName>
    <GenerateAssemblyInfo>True</GenerateAssemblyInfo>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <Copyright>Copyright © Kozupitsa DmA $(Year)</Copyright>
    <Title>PasswordGenerator</Title>
    <Description>
      Cryptographic password generator for .NET with flexible customization of character sets (lowercase, uppercase, numbers, special characters), length and number of additional characters. Supports INotifyPropertyChanged for easy integration with the UI and guarantees the presence of each selected character type in the final password.
    </Description>
    <Product>PasswordGenerator</Product>
    <AssemblyVersion Condition=" '$(VersionSuffix)' == '' ">1.0.0.0</AssemblyVersion>
    <AssemblyVersion Condition=" '$(VersionSuffix)' != '' ">$(VersionSuffix)</AssemblyVersion>
    <Version Condition=" '$(VersionSuffix)' == '' ">1.0.0.0</Version>
    <Version Condition=" '$(VersionSuffix)' != '' ">$(VersionSuffix)</Version>
    <PackageLicenseFile>Readme.txt</PackageLicenseFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <PackageOutputPath>..\..\..\..\Nuget</PackageOutputPath>
    <PackageProjectUrl>https://github.com/dimsaratov/PasswordGenerator</PackageProjectUrl>
    <RepositoryUrl>https://github.com/dimsaratov/PasswordGenerator</RepositoryUrl>
    <PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageTags>Password_generation Password_generator</PackageTags>
  </PropertyGroup>

 
  <ItemGroup>
     
    <None Update="BuildTime.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>BuildTime.txt</LastGenOutput>
    </None>
     
    <None Update="BuildTime.txt">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>BuildTime.tt</DependentUpon>
    </None>
     
    <None Update="LICENSE.tt">
        <Generator>TextTemplatingFileGenerator</Generator>
        <LastGenOutput>LICENSE.txt</LastGenOutput>
        <CopyToOutputDirectory>Never</CopyToOutputDirectory>
      </None>

      <None Include="LICENSE.txt" Pack="true" PackagePath="\">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>LICENSE.tt</DependentUpon>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
     
    <None Update="Readme.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>Readme.md</LastGenOutput>
    </None>     
    
    <None Include="README.md" Pack="true" PackagePath="\">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Readme.tt</DependentUpon>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
 
  
  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

</Project>
